// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyR6VocYLXmQPX4PGXb82hRA-5tEtLog4',
    appId: '1:918264471231:web:f964e6214591a1cb6e700a',
    messagingSenderId: '918264471231',
    projectId: 'ostad-1ee9b',
    authDomain: 'ostad-1ee9b.firebaseapp.com',
    storageBucket: 'ostad-1ee9b.firebasestorage.app',
    measurementId: 'G-MLXXFSGJ2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Kgr4A9lxZ3y8QeXx-rwpuJMyyvjdflw',
    appId: '1:918264471231:android:6201183de8f182696e700a',
    messagingSenderId: '918264471231',
    projectId: 'ostad-1ee9b',
    storageBucket: 'ostad-1ee9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvCcXtZM9xVT3OEsw42M2S8wW4dnVKrQk',
    appId: '1:918264471231:ios:d168ccc085190b546e700a',
    messagingSenderId: '918264471231',
    projectId: 'ostad-1ee9b',
    storageBucket: 'ostad-1ee9b.firebasestorage.app',
    iosBundleId: 'com.example.meathub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvCcXtZM9xVT3OEsw42M2S8wW4dnVKrQk',
    appId: '1:918264471231:ios:d168ccc085190b546e700a',
    messagingSenderId: '918264471231',
    projectId: 'ostad-1ee9b',
    storageBucket: 'ostad-1ee9b.firebasestorage.app',
    iosBundleId: 'com.example.meathub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyR6VocYLXmQPX4PGXb82hRA-5tEtLog4',
    appId: '1:918264471231:web:28b63da094efedc96e700a',
    messagingSenderId: '918264471231',
    projectId: 'ostad-1ee9b',
    authDomain: 'ostad-1ee9b.firebaseapp.com',
    storageBucket: 'ostad-1ee9b.firebasestorage.app',
    measurementId: 'G-PK47GVDSFT',
  );
}
